import "@/styles/index.css";
import "@/assets/css/style.css";
import "@/assets/css/plugins.css";

import type { Metadata } from "next";
import { redirect, RedirectType } from "next/navigation";

import ReduxProvider from "@/components/ReduxProvider";
import { auth } from "@/lib/next-auth";
import { initDB } from "@/database";
import ResponsiveAppBar from "@/components/Header";

export const metadata: Metadata = {
  title: "hiring-portal",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = async ({ children }: RootLayoutProps) => {
  await initDB();
  const session = await auth();

  if (!session?.user?.id) {
    redirect("/auth/login", RedirectType.replace);
  }

  return (
    <html lang="en">
      <body className="bg-background text-foreground min-h-screen">
        <ReduxProvider>
          <ResponsiveAppBar session={session} />
          <main className="pt-20 px-4">{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
